"""
Django settings for EasyConnectMD project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.conf import settings
from django.conf.urls.static import static

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'gk)#z-uq9s$bjt(_xjqckfxv%lpfyq2xevdmr#jd!q9din!#m9'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'gk)#z-uq9s$bjt(_xjqckfxv%lpfyq2xevdmr#jd!q9din!#m9')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = DEBUG = os.environ.get('DJANGO_DEBUG', '') != 'False'

ALLOWED_HOSTS = ['easyconnectmd.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'EasyConnect.apps.EasyconnectConfig',
    'phonenumber_field',
    "django_select2",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EasyConnectMD.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EasyConnectMD.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
# sudo apt install python3-dev libpq-dev
# pip install psycopg2S
# create db user account
# open ports
# in postgres ALTER USER username PASSWORD = "password";
if DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'easyconnect',
            'USER': 'easyconnect',
            'PASSWORD': 'abacabb',
            'HOST': '216.177.177.7',
            'PORT': '5432',
        }
    }
    # redis Cache https://django-select2.readthedocs.io/en/latest/
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://216.177.177.7:6379/1",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        },
        'select2': {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://192.168.1.122:6379/2",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'easyconnectmd_dev',
            'USER': 'easyconnectmd_devUser',
            'PASSWORD': 'u435Wz8STwWZBdkA2tn9Y%wp7Chz8M!!qV^sj9MHNyw3fqe@F5',
            'HOST': '127.0.0.1',
            'PORT': '5432',
        }
    }
    # redis Cache https://django-select2.readthedocs.io/en/latest/
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://127.0.0.1:6379/1",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        },
        'select2': {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://127.0.0.1:6379/2",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Set the cache backend to select2
SELECT2_CACHE_BACKEND = 'select2'

LOGIN_REDIRECT_URL = 'easyconnect:dashboard'
LOGOUT_REDIRECT_URL = 'easyconnect:dashboard'

# phone number representation
PHONENUMBER_DB_FORMAT = 'NATIONAL'
PHONENUMBER_DEFAULT_REGION = 'US'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
# Payment keys for Square
if DEBUG:
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, "static/")
    STATICFILES_DIR = (
        os.path.join(BASE_DIR, 'EasyConnect/static')
    )
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, "static_media")

    SQUARE_APP_ID = 'sandbox-sq0idb-tOPCaqqjNhHwoh3Vi_ihkg'
    SQUARE_ACCESS_TOKEN = 'EAAAEEIFPF_5Utik58cM9dKzOjqh_f0IpljAftfPdwo36EFxWRUjExV9I1Y30pBf'
else:
    STATIC_URL = '/static/'
    STATIC_ROOT = os.path.join(BASE_DIR, 'static_files')
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, "static_media")

    SQUARE_APP_ID = 'sq0idp-vxCXwuvwxA919yaoe5wczQ'
    SQUARE_ACCESS_TOKEN = 'EAAAELBWv5rGYdtNtubLvPBZEXR5vb0yav0RypCREkZnRoPkOQfcETJL0C6MxmFR'